# Site settings
title: Rodion Malinovsky - Personal Website
email: rodionmalino@gmail.com
description: I'm Rodion. I'm Team Lead & Software Developer.
url: "https://malirod.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  hard_wrap: false

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Rodion Malinovsky"
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page/:num"
comments: true
