# Site settings
title: Rodion Malinovsky - Personal Website
email: rodionmalino@gmail.com
description: I'm Renato. I am Front End Developer and Designer based in Croatia. I'm always availible for freelance work. Contact me!
url: "https://malirod.github.io/" 

# Build settings
markdown: kramdown
permalink: pretty

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Rodion Malinovsky"
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

# Gems
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/blog/page/:num"
